
USE hackosean;

CREATE TABLE datospago ( 
	id INT IDENTITY(1,1) NOT NULL ,
	Nombre VARCHAR(50) NOT NULL ,
	NombreDonador VARCHAR(50) NOT NULL ,
	Pago INT NOT NULL ,
	MSG VARCHAR(100) NOT NULL ,
	PRIMARY KEY (id)
);

CREATE TABLE datoscandidatos ( 
	id INT IDENTITY(1,1) NOT NULL ,
	Nombre VARCHAR(50) NOT NULL ,
	Edad INT NOT NULL ,
	Correo VARCHAR(70) NOT NULL ,
	PRIMARY KEY (id)
) ;
